name: Build and containerise saturn

on:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Build Container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: saturn
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: Push to GHCR.io
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          image: saturn
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
